# Generated by Django 2.0.1 on 2018-01-18 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='escuelas',
            name='monto_restante',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='escuelas',
            name='observacion',
            field=models.TextField(default='Sin observación'),
        ),
    ]
