# Generated by Django 2.0 on 2018-01-21 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0003_auto_20180120_1409'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sispre',
            name='cierre',
        ),
        migrations.RemoveField(
            model_name='sispre',
            name='inicio',
        ),
        migrations.RemoveField(
            model_name='sispre',
            name='seguimiento',
        ),
        migrations.AddField(
            model_name='sispre',
            name='acta_mArchivo',
            field=models.FileField(blank=True, null=True, upload_to='PDF/SiSPRE/Inicio/'),
        ),
        migrations.AddField(
            model_name='sispre',
            name='acta_mObservacion',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='sispre',
            name='acta_mancomunado',
            field=models.CharField(choices=[('Sin Datos', 'Sin Datos'), ('En revisión', 'En revisión'), ('Corregir', 'Corregir'), ('Correcto', 'Correcto')], default=False, max_length=40),
        ),
        migrations.AddField(
            model_name='sispre',
            name='acta_pArchivo',
            field=models.FileField(blank=True, null=True, upload_to='PDF/SiSPRE/Inicio/'),
        ),
        migrations.AddField(
            model_name='sispre',
            name='acta_pObservacion',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='sispre',
            name='acta_planeacion',
            field=models.CharField(choices=[('Sin Datos', 'Sin Datos'), ('En revisión', 'En revisión'), ('Corregir', 'Corregir'), ('Correcto', 'Correcto')], default=False, max_length=40),
        ),
        migrations.AddField(
            model_name='sispre',
            name='acuse_bArchivo',
            field=models.FileField(blank=True, null=True, upload_to='PDF/SiSPRE/Inicio/'),
        ),
        migrations.AddField(
            model_name='sispre',
            name='acuse_bObservacion',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='sispre',
            name='acuse_banco',
            field=models.CharField(choices=[('No Aplica', 'No Aplica'), ('Mayor', 'Mayor'), ('Menor', 'Menor')], default='No Aplica', max_length=25),
        ),
        migrations.AddField(
            model_name='sispre',
            name='acuse_pArchivo',
            field=models.FileField(blank=True, null=True, upload_to='PDF/SiSPRE/Inicio/'),
        ),
        migrations.AddField(
            model_name='sispre',
            name='acuse_pObservacion',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='sispre',
            name='acuse_prog',
            field=models.CharField(choices=[('Sin Datos', 'Sin Datos'), ('En revisión', 'En revisión'), ('Corregir', 'Corregir'), ('Correcto', 'Correcto')], default=False, max_length=40),
        ),
        migrations.AddField(
            model_name='sispre',
            name='acuse_prog_aArchivo',
            field=models.FileField(blank=True, null=True, upload_to='PDF/SiSPRE/Inicio/'),
        ),
        migrations.AddField(
            model_name='sispre',
            name='acuse_prog_aObservacion',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='sispre',
            name='acuse_prog_anterior',
            field=models.CharField(choices=[('No Aplica', 'No Aplica'), ('Mayor', 'Mayor'), ('Menor', 'Menor')], default='No Aplica', max_length=25),
        ),
        migrations.AddField(
            model_name='sispre',
            name='comision_dArchivo',
            field=models.FileField(blank=True, null=True, upload_to='PDF/SiSPRE/Inicio/'),
        ),
        migrations.AddField(
            model_name='sispre',
            name='comision_dObservacion',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='sispre',
            name='comision_director',
            field=models.CharField(choices=[('Sin Datos', 'Sin Datos'), ('En revisión', 'En revisión'), ('Corregir', 'Corregir'), ('Correcto', 'Correcto')], default=False, max_length=40),
        ),
        migrations.AddField(
            model_name='sispre',
            name='compromiso_cArchivo',
            field=models.FileField(blank=True, null=True, upload_to='PDF/SiSPRE/Inicio/'),
        ),
        migrations.AddField(
            model_name='sispre',
            name='compromiso_cObservacion',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='sispre',
            name='compromiso_comunidad',
            field=models.CharField(choices=[('Sin Datos', 'Sin Datos'), ('En revisión', 'En revisión'), ('Corregir', 'Corregir'), ('Correcto', 'Correcto')], default=False, max_length=40),
        ),
        migrations.AddField(
            model_name='sispre',
            name='compromiso_iArchivo',
            field=models.FileField(blank=True, null=True, upload_to='PDF/SiSPRE/Inicio/'),
        ),
        migrations.AddField(
            model_name='sispre',
            name='compromiso_iObservacion',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='sispre',
            name='compromiso_inmueble',
            field=models.CharField(choices=[('No Aplica', 'No Aplica'), ('Mayor', 'Mayor'), ('Menor', 'Menor')], default='No Aplica', max_length=25),
        ),
        migrations.AddField(
            model_name='sispre',
            name='constancia_cArchivo',
            field=models.FileField(blank=True, null=True, upload_to='PDF/SiSPRE/Inicio/'),
        ),
        migrations.AddField(
            model_name='sispre',
            name='constancia_cObservacion',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='sispre',
            name='constancia_cepse',
            field=models.CharField(choices=[('Sin Datos', 'Sin Datos'), ('En revisión', 'En revisión'), ('Corregir', 'Corregir'), ('Correcto', 'Correcto')], default=False, max_length=40),
        ),
        migrations.AddField(
            model_name='sispre',
            name='contrato',
            field=models.CharField(choices=[('No Aplica', 'No Aplica'), ('Mayor', 'Mayor'), ('Menor', 'Menor')], default='No Aplica', max_length=25),
        ),
        migrations.AddField(
            model_name='sispre',
            name='contratoArchivo',
            field=models.FileField(blank=True, null=True, upload_to='PDF/SiSPRE/Inicio/'),
        ),
        migrations.AddField(
            model_name='sispre',
            name='contratoObservacion',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='sispre',
            name='estatusI',
            field=models.CharField(choices=[('Incompleto', 'Incompleto'), ('Completo', 'Completo')], default='Incompleto', max_length=20),
        ),
        migrations.AddField(
            model_name='sispre',
            name='foto_fachada',
            field=models.ImageField(blank=True, default='Fotos/Fotos_Fachada/None/no-img.png', upload_to='Fotos/Fotos_Fachada/'),
        ),
        migrations.AddField(
            model_name='sispre',
            name='ife_cArchivo',
            field=models.FileField(blank=True, null=True, upload_to='PDF/SiSPRE/Inicio/'),
        ),
        migrations.AddField(
            model_name='sispre',
            name='ife_cObservacion',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='sispre',
            name='ife_cepse',
            field=models.CharField(choices=[('Sin Datos', 'Sin Datos'), ('En revisión', 'En revisión'), ('Corregir', 'Corregir'), ('Correcto', 'Correcto')], default=False, max_length=40),
        ),
        migrations.AddField(
            model_name='sispre',
            name='ife_pArchivo',
            field=models.FileField(blank=True, null=True, upload_to='PDF/SiSPRE/Inicio/'),
        ),
        migrations.AddField(
            model_name='sispre',
            name='ife_pObservacion',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='sispre',
            name='ife_plantel',
            field=models.CharField(choices=[('Sin Datos', 'Sin Datos'), ('En revisión', 'En revisión'), ('Corregir', 'Corregir'), ('Correcto', 'Correcto')], default=False, max_length=40),
        ),
        migrations.AddField(
            model_name='sispre',
            name='observacion',
            field=models.TextField(default='Sin observaciones'),
        ),
    ]
