# Generated by Django 2.0 on 2018-01-21 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0005_auto_20180120_2054'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contraloria_social',
            name='pdf_anual',
        ),
        migrations.RemoveField(
            model_name='contraloria_social',
            name='pdf_constitucion',
        ),
        migrations.RemoveField(
            model_name='contraloria_social',
            name='pdf_seguimiento',
        ),
        migrations.AddField(
            model_name='contraloria_social',
            name='acta_aArchivo',
            field=models.FileField(blank=True, null=True, upload_to='PDF/SiSPRE/Inicio/'),
        ),
        migrations.AddField(
            model_name='contraloria_social',
            name='acta_aObservacion',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='contraloria_social',
            name='acta_cArchivo',
            field=models.FileField(blank=True, null=True, upload_to='PDF/SiSPRE/Inicio/'),
        ),
        migrations.AddField(
            model_name='contraloria_social',
            name='acta_cObservacion',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='contraloria_social',
            name='acta_sArchivo',
            field=models.FileField(blank=True, null=True, upload_to='PDF/SiSPRE/Inicio/'),
        ),
        migrations.AddField(
            model_name='contraloria_social',
            name='acta_sObservacion',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='contraloria_social',
            name='foto_aArchivo',
            field=models.FileField(blank=True, null=True, upload_to='PDF/SiSPRE/Inicio/'),
        ),
        migrations.AddField(
            model_name='contraloria_social',
            name='foto_aObservacion',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='contraloria_social',
            name='foto_cArchivo',
            field=models.FileField(blank=True, null=True, upload_to='PDF/SiSPRE/Inicio/'),
        ),
        migrations.AddField(
            model_name='contraloria_social',
            name='foto_cObservacion',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='contraloria_social',
            name='foto_sArchivo',
            field=models.FileField(blank=True, null=True, upload_to='PDF/SiSPRE/Inicio/'),
        ),
        migrations.AddField(
            model_name='contraloria_social',
            name='foto_sObservacion',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='contraloria_social',
            name='lista_aArchivo',
            field=models.FileField(blank=True, null=True, upload_to='PDF/SiSPRE/Inicio/'),
        ),
        migrations.AddField(
            model_name='contraloria_social',
            name='lista_aObservacion',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='contraloria_social',
            name='lista_cArchivo',
            field=models.FileField(blank=True, null=True, upload_to='PDF/SiSPRE/Inicio/'),
        ),
        migrations.AddField(
            model_name='contraloria_social',
            name='lista_cObservacion',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='contraloria_social',
            name='lista_sArchivo',
            field=models.FileField(blank=True, null=True, upload_to='PDF/SiSPRE/Inicio/'),
        ),
        migrations.AddField(
            model_name='contraloria_social',
            name='lista_sObservacion',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='contraloria_social',
            name='minuta_aArchivo',
            field=models.FileField(blank=True, null=True, upload_to='PDF/SiSPRE/Inicio/'),
        ),
        migrations.AddField(
            model_name='contraloria_social',
            name='minuta_aObservacion',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='contraloria_social',
            name='minuta_cArchivo',
            field=models.FileField(blank=True, null=True, upload_to='PDF/SiSPRE/Inicio/'),
        ),
        migrations.AddField(
            model_name='contraloria_social',
            name='minuta_cObservacion',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='contraloria_social',
            name='minuta_sArchivo',
            field=models.FileField(blank=True, null=True, upload_to='PDF/SiSPRE/Inicio/'),
        ),
        migrations.AddField(
            model_name='contraloria_social',
            name='minuta_sObservacion',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='contraloria_social',
            name='acta_anual',
            field=models.CharField(choices=[('Sin Datos', 'Sin Datos'), ('En revisión', 'En revisión'), ('Corregir', 'Corregir'), ('Correcto', 'Correcto')], default=False, max_length=40),
        ),
        migrations.AlterField(
            model_name='contraloria_social',
            name='acta_constitucion',
            field=models.CharField(choices=[('Sin Datos', 'Sin Datos'), ('En revisión', 'En revisión'), ('Corregir', 'Corregir'), ('Correcto', 'Correcto')], default=False, max_length=40),
        ),
        migrations.AlterField(
            model_name='contraloria_social',
            name='acta_seguimiento',
            field=models.CharField(choices=[('Sin Datos', 'Sin Datos'), ('En revisión', 'En revisión'), ('Corregir', 'Corregir'), ('Correcto', 'Correcto')], default=False, max_length=40),
        ),
        migrations.AlterField(
            model_name='contraloria_social',
            name='cd_anual',
            field=models.CharField(choices=[('No', 'No'), ('Si', 'Si')], default='No', max_length=10),
        ),
        migrations.AlterField(
            model_name='contraloria_social',
            name='cd_constitucion',
            field=models.CharField(choices=[('No', 'No'), ('Si', 'Si')], default='No', max_length=10),
        ),
        migrations.AlterField(
            model_name='contraloria_social',
            name='cd_seguimiento',
            field=models.CharField(choices=[('No', 'No'), ('Si', 'Si')], default='No', max_length=10),
        ),
        migrations.AlterField(
            model_name='contraloria_social',
            name='foto_anual',
            field=models.CharField(choices=[('Sin Datos', 'Sin Datos'), ('En revisión', 'En revisión'), ('Corregir', 'Corregir'), ('Correcto', 'Correcto')], default=False, max_length=40),
        ),
        migrations.AlterField(
            model_name='contraloria_social',
            name='foto_constitucion',
            field=models.CharField(choices=[('Sin Datos', 'Sin Datos'), ('En revisión', 'En revisión'), ('Corregir', 'Corregir'), ('Correcto', 'Correcto')], default=False, max_length=40),
        ),
        migrations.AlterField(
            model_name='contraloria_social',
            name='foto_seguimiento',
            field=models.CharField(choices=[('Sin Datos', 'Sin Datos'), ('En revisión', 'En revisión'), ('Corregir', 'Corregir'), ('Correcto', 'Correcto')], default=False, max_length=40),
        ),
        migrations.AlterField(
            model_name='contraloria_social',
            name='lista_anual',
            field=models.CharField(choices=[('Sin Datos', 'Sin Datos'), ('En revisión', 'En revisión'), ('Corregir', 'Corregir'), ('Correcto', 'Correcto')], default=False, max_length=40),
        ),
        migrations.AlterField(
            model_name='contraloria_social',
            name='lista_constitucion',
            field=models.CharField(choices=[('Sin Datos', 'Sin Datos'), ('En revisión', 'En revisión'), ('Corregir', 'Corregir'), ('Correcto', 'Correcto')], default=False, max_length=40),
        ),
        migrations.AlterField(
            model_name='contraloria_social',
            name='lista_seguimiento',
            field=models.CharField(choices=[('Sin Datos', 'Sin Datos'), ('En revisión', 'En revisión'), ('Corregir', 'Corregir'), ('Correcto', 'Correcto')], default=False, max_length=40),
        ),
        migrations.AlterField(
            model_name='contraloria_social',
            name='minuta_anual',
            field=models.CharField(choices=[('Sin Datos', 'Sin Datos'), ('En revisión', 'En revisión'), ('Corregir', 'Corregir'), ('Correcto', 'Correcto')], default=False, max_length=40),
        ),
        migrations.AlterField(
            model_name='contraloria_social',
            name='minuta_constitucion',
            field=models.CharField(choices=[('Sin Datos', 'Sin Datos'), ('En revisión', 'En revisión'), ('Corregir', 'Corregir'), ('Correcto', 'Correcto')], default=False, max_length=40),
        ),
        migrations.AlterField(
            model_name='contraloria_social',
            name='minuta_seguimiento',
            field=models.CharField(choices=[('Sin Datos', 'Sin Datos'), ('En revisión', 'En revisión'), ('Corregir', 'Corregir'), ('Correcto', 'Correcto')], default=False, max_length=40),
        ),
    ]
