# Generated by Django 2.0 on 2018-01-21 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0006_auto_20180120_2139'),
    ]

    operations = [
        migrations.AddField(
            model_name='contraloria_social',
            name='estatusA',
            field=models.CharField(choices=[('Incompleto', 'Incompleto'), ('Completo', 'Completo')], default='Incompleto', max_length=20),
        ),
        migrations.AddField(
            model_name='contraloria_social',
            name='estatusC',
            field=models.CharField(choices=[('Incompleto', 'Incompleto'), ('Completo', 'Completo')], default='Incompleto', max_length=20),
        ),
        migrations.AddField(
            model_name='contraloria_social',
            name='estatusS',
            field=models.CharField(choices=[('Incompleto', 'Incompleto'), ('Completo', 'Completo')], default='Incompleto', max_length=20),
        ),
        migrations.AddField(
            model_name='contraloria_social',
            name='pdf_anual',
            field=models.FileField(blank=True, null=True, upload_to='PDF/Contraloria_S/Anual/'),
        ),
        migrations.AddField(
            model_name='contraloria_social',
            name='pdf_constitucion',
            field=models.FileField(blank=True, null=True, upload_to='PDF/Contraloria_S/Inicio/'),
        ),
        migrations.AddField(
            model_name='contraloria_social',
            name='pdf_seguimiento',
            field=models.FileField(blank=True, null=True, upload_to='PDF/Contraloria_S/Seguimiento/'),
        ),
        migrations.AddField(
            model_name='escuelas',
            name='contraloria_s',
            field=models.ForeignKey(default=1, on_delete=False, to='Admin.Contraloria_Social'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contraloria_social',
            name='acta_aArchivo',
            field=models.FileField(blank=True, null=True, upload_to='PDF/Contraloria_S/Anual/'),
        ),
        migrations.AlterField(
            model_name='contraloria_social',
            name='acta_cArchivo',
            field=models.FileField(blank=True, null=True, upload_to='PDF/Contraloria_S/Inicio/'),
        ),
        migrations.AlterField(
            model_name='contraloria_social',
            name='acta_sArchivo',
            field=models.FileField(blank=True, null=True, upload_to='PDF/Contraloria_S/Seguimiento/'),
        ),
        migrations.AlterField(
            model_name='contraloria_social',
            name='foto_aArchivo',
            field=models.FileField(blank=True, null=True, upload_to='PDF/Contraloria_S/Anual/Fotos/'),
        ),
        migrations.AlterField(
            model_name='contraloria_social',
            name='foto_cArchivo',
            field=models.FileField(blank=True, null=True, upload_to='PDF/Contraloria_S/Inicio/Fotos/'),
        ),
        migrations.AlterField(
            model_name='contraloria_social',
            name='foto_sArchivo',
            field=models.FileField(blank=True, null=True, upload_to='PDF/Contraloria_S/Seguimiento/Fotos/'),
        ),
        migrations.AlterField(
            model_name='contraloria_social',
            name='lista_aArchivo',
            field=models.FileField(blank=True, null=True, upload_to='PDF/Contraloria_S/Anual/'),
        ),
        migrations.AlterField(
            model_name='contraloria_social',
            name='lista_cArchivo',
            field=models.FileField(blank=True, null=True, upload_to='PDF/Contraloria_S/Inicio/'),
        ),
        migrations.AlterField(
            model_name='contraloria_social',
            name='lista_sArchivo',
            field=models.FileField(blank=True, null=True, upload_to='PDF/Contraloria_S/Seguimiento/'),
        ),
        migrations.AlterField(
            model_name='contraloria_social',
            name='minuta_aArchivo',
            field=models.FileField(blank=True, null=True, upload_to='PDF/Contraloria_S/Anual/'),
        ),
        migrations.AlterField(
            model_name='contraloria_social',
            name='minuta_cArchivo',
            field=models.FileField(blank=True, null=True, upload_to='PDF/Contraloria_S/Inicio/'),
        ),
        migrations.AlterField(
            model_name='contraloria_social',
            name='minuta_sArchivo',
            field=models.FileField(blank=True, null=True, upload_to='PDF/Contraloria_S/Seguimiento/'),
        ),
    ]
