# Generated by Django 2.0 on 2018-01-22 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0008_auto_20180122_0925'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fechas_Finales',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField(blank=True, null=True)),
                ('fecha_seguimiento', models.DateField(blank=True, null=True)),
                ('fecha_cierre', models.DateField(blank=True, null=True)),
                ('fecha_constitucion', models.DateField(blank=True, null=True)),
                ('fecha_seguimientoC', models.DateField(blank=True, null=True)),
                ('fecha_anual', models.DateField(blank=True, null=True)),
                ('actualizacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['actualizacion'],
                'verbose_name_plural': 'Fecha de Entregas',
            },
        ),
        migrations.AddField(
            model_name='sispre',
            name='fechas_entregas',
            field=models.ForeignKey(default=1, on_delete=False, to='Admin.Fechas_Finales'),
            preserve_default=False,
        ),
    ]
