# Generated by Django 2.0 on 2018-01-22 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0009_auto_20180122_0943'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contraloria_social',
            name='estatus',
        ),
        migrations.AlterField(
            model_name='sispre',
            name='fechas_entregas',
            field=models.ForeignKey(blank=True, null=True, on_delete=False, to='Admin.Fechas_Finales'),
        ),
    ]
