# Generated by Django 2.0 on 2018-01-22 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0011_contraloria_social_fechas_entregas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contraloria_social',
            name='fechas_entregas',
        ),
        migrations.RemoveField(
            model_name='sispre',
            name='fechas_entregas',
        ),
    ]
