# Generated by Django 2.0 on 2018-01-23 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0013_auto_20180123_0935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cierres',
            name='acta_cierre',
            field=models.CharField(choices=[('Sin Datos', 'Sin Datos'), ('En revisión', 'En revisión'), ('Corregir', 'Corregir'), ('Correcto', 'Correcto')], default=False, max_length=40),
        ),
    ]
