# Generated by Django 2.0.1 on 2018-02-06 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0018_auto_20180130_2116'),
    ]

    operations = [
        migrations.CreateModel(
            name='Documentos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acta_mancomunado', models.FileField(blank=True, null=True, upload_to='Cuadernillo/Inicio/')),
                ('constancia_cepse', models.FileField(blank=True, null=True, upload_to='Cuadernillo/Inicio/')),
                ('acta_planeacion', models.FileField(blank=True, null=True, upload_to='Cuadernillo/Inicio/')),
                ('acuse_prog', models.FileField(blank=True, null=True, upload_to='Cuadernillo/Inicio/')),
                ('compromiso_inmueble', models.FileField(blank=True, null=True, upload_to='Cuadernillo/Inicio/')),
                ('compromiso_comunidad', models.FileField(blank=True, null=True, upload_to='Cuadernillo/Inicio/')),
                ('contrato', models.FileField(blank=True, null=True, upload_to='Cuadernillo/Inicio/')),
                ('acta_cierre', models.FileField(blank=True, null=True, upload_to='Cuadernillo/Cierre/')),
                ('acta_entrega', models.FileField(blank=True, null=True, upload_to='Cuadernillo/Cierre/')),
                ('acta_rendicion', models.FileField(blank=True, null=True, upload_to='Cuadernillo/Cierre/')),
                ('ficha_reintegro', models.FileField(blank=True, null=True, upload_to='Cuadernillo/Cierre/')),
                ('form_inventario', models.FileField(blank=True, null=True, upload_to='Cuadernillo/Cierre/')),
                ('form_transferencia', models.FileField(blank=True, null=True, upload_to='Cuadernillo/Cierre/')),
                ('registro_gastos', models.FileField(blank=True, null=True, upload_to='Cuadernillo/Cierre/')),
                ('verificacion_sat', models.FileField(blank=True, null=True, upload_to='Cuadernillo/Cierre/')),
            ],
        ),
        migrations.RemoveField(
            model_name='cierres',
            name='resumen_gArchivo',
        ),
        migrations.RemoveField(
            model_name='cierres',
            name='resumen_gObservacion',
        ),
        migrations.RemoveField(
            model_name='cierres',
            name='resumen_gastos',
        ),
        migrations.RemoveField(
            model_name='sispre',
            name='seguimiento',
        ),
    ]
