# Generated by Django 2.0.1 on 2018-02-06 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0019_auto_20180206_1357'),
    ]

    operations = [
        migrations.AddField(
            model_name='inicios',
            name='registro_gArchivo',
            field=models.FileField(blank=True, null=True, upload_to='PDF/SiSPRE/Cierre/'),
        ),
        migrations.AddField(
            model_name='inicios',
            name='registro_gObservacion',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='inicios',
            name='registro_gastos',
            field=models.CharField(choices=[('Sin Datos', 'Sin Datos'), ('En revisión', 'En revisión'), ('Corregir', 'Corregir'), ('Correcto', 'Correcto')], default='No Aplica', max_length=40),
        ),
    ]
