# Generated by Django 2.0.1 on 2018-02-06 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0020_auto_20180206_1404'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inicios',
            old_name='registro_gArchivo',
            new_name='registro_aArchivo',
        ),
        migrations.RenameField(
            model_name='inicios',
            old_name='registro_gObservacion',
            new_name='registro_aObservacion',
        ),
        migrations.RenameField(
            model_name='inicios',
            old_name='registro_gastos',
            new_name='registro_asignado',
        ),
    ]
