# Generated by Django 2.0.1 on 2018-02-06 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0021_auto_20180206_1429'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cierres',
            old_name='estatus',
            new_name='estatusCierreS',
        ),
        migrations.RenameField(
            model_name='inicios',
            old_name='estatus',
            new_name='estatusInicioS',
        ),
    ]
