# Generated by Django 2.0.1 on 2018-02-06 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0022_auto_20180206_1444'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cierres',
            old_name='observacion',
            new_name='observacionCierre',
        ),
        migrations.RenameField(
            model_name='documentos',
            old_name='acta_cierre',
            new_name='PDF_acta_cierre',
        ),
        migrations.RenameField(
            model_name='documentos',
            old_name='acta_entrega',
            new_name='PDF_acta_entrega',
        ),
        migrations.RenameField(
            model_name='documentos',
            old_name='acta_mancomunado',
            new_name='PDF_acta_mancomunado',
        ),
        migrations.RenameField(
            model_name='documentos',
            old_name='acta_planeacion',
            new_name='PDF_acta_planeacion',
        ),
        migrations.RenameField(
            model_name='documentos',
            old_name='acta_rendicion',
            new_name='PDF_acta_rendicion',
        ),
        migrations.RenameField(
            model_name='documentos',
            old_name='acuse_prog',
            new_name='PDF_acuse_prog',
        ),
        migrations.RenameField(
            model_name='documentos',
            old_name='compromiso_comunidad',
            new_name='PDF_compromiso_comunidad',
        ),
        migrations.RenameField(
            model_name='documentos',
            old_name='compromiso_inmueble',
            new_name='PDF_compromiso_inmueble',
        ),
        migrations.RenameField(
            model_name='documentos',
            old_name='constancia_cepse',
            new_name='PDF_constancia_cepse',
        ),
        migrations.RenameField(
            model_name='documentos',
            old_name='contrato',
            new_name='PDF_contrato',
        ),
        migrations.RenameField(
            model_name='documentos',
            old_name='ficha_reintegro',
            new_name='PDF_ficha_reintegro',
        ),
        migrations.RenameField(
            model_name='documentos',
            old_name='form_inventario',
            new_name='PDF_form_inventario',
        ),
        migrations.RenameField(
            model_name='documentos',
            old_name='form_transferencia',
            new_name='PDF_form_transferencia',
        ),
        migrations.RenameField(
            model_name='documentos',
            old_name='registro_gastos',
            new_name='PDF_registro_gastos',
        ),
        migrations.RenameField(
            model_name='documentos',
            old_name='verificacion_sat',
            new_name='PDF_verificacion_sat',
        ),
    ]
